<?php 
/**
* @var \NttData\Practice\Block\Test $block
*/
?>
<div class="cajaProductList">
    <?= $block->getInfoClass() ?>
<hr>

<?php
    $ids = [1,2,3];
    $categoryProducts = $block->getProductCollectionByCategories($ids);
?>

<?php if($block -> isEnabled()): ?>
    <span>Settingf on</span>
<?php else:?>
    <span>Settings off</span>
<?php endif;?>
<?php if($block->isEnabled()):?>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>URL Path</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($categoryProducts as $product):?>
                <tr>
                    <td><?= $product->getId() ?></td>
                    <td><?= $product->getName() ?></td>
                    <td><?= $product->getDescription()?></td>
                    <td><?= $product->getProductUrl() ?></td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
<?php endif;?>